[package]
name = "waved"
version = "0.1.0"
description = ""
authors = ["Joel Robichaud <robichaud.jo@gmail.com>"]
edition = "2018"

[dependencies]
glfw = "0.26.0"
nfd = "0.0.4"
portaudio = "0.7.0"
nom = "4.2.0"

[package.metadata.bundle]
# name = "Waved"
identifier = "com.joelrobichaud.waved"
# icon = []
# version = "0.1.0"
# resources = []
copyright = "Copyright (c) Joel Robichaud 2019. All rights reserved."
# category = ""
# short_description = ""
# long_description = """
# """
# deb_depends = []
# osx_frameworks = []
