[package]
name = "waved"
version = "0.1.0"
description = ""
authors = ["Joel Robichaud <robichaud.jo@gmail.com>"]
edition = "2018"

[dependencies]
glfw = "0.26.1"
cairo-rs = "0.5.0"
nfd = "0.0.4"
portaudio = "0.7.0"
nom = "4.2.0"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.18.4"
core-graphics = "0.17.3"
foreign-types = "0.3.2"
objc = "0.2.5"

[package.metadata.bundle]
# name = "Waved"
identifier = "com.joelrobichaud.waved"
# icon = []
# version = "0.1.0"
# resources = []
copyright = "Copyright (c) Joel Robichaud 2019. All rights reserved."
# category = ""
# short_description = ""
# long_description = """
# """
# deb_depends = []
# osx_frameworks = []
