[package]
name = "waved-core"
version = "0.1.0"
authors = ["Joel Robichaud <robichaud.jo@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
nanovg = { version = "1.0.2", features = ["gl3"] }
