[package]
name = "waved-sndfile"
version = "0.1.0"
authors = ["Joel Robichaud <robichaud.jo@gmail.com>"]
edition = "2018"

[dependencies]
hound = "3.4.0"
cpal = "0.11.0"
ringbuf = "0.2.1"
itertools = "0.9.0"
